services:
  pdmx:
    image: ${REPOSITORY:-quay.io/telosalliance/pdmx}:${TAG:-latest}
    container_name: pdmx-${INSTANCE_NAME}
    hostname: pdmx-${INSTANCE_NAME}
    restart: unless-stopped
    sysctls:
      #### Make sure tcp sockets fail quickly if network dies ####
      # Idle time until first keepalive packet sent
      - net.ipv4.tcp_keepalive_time=3
      # Time between subsequent keepalive packets
      - net.ipv4.tcp_keepalive_intvl=3
      # How many keepalive packets before declare connection dead
      - net.ipv4.tcp_keepalive_probes=3
      # Number of retries of unacknowledged packets (exponential backoff; about 12 seconds)
      - net.ipv4.tcp_retries2=5
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    environment:
      - STUDIO=${INSTANCE_NAME}
      - IFACE_AOIP=${IFACE_AOIP:-eth1}
    networks:
      telosmacvlan:
        ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
      ext1macvlan:
        ipv4_address: ${IFACE_EXT_IPV4_ADDRESS}
    volumes:
      - /dev/log:/dev/log
      - /opt/telos/pdmx-${INSTANCE_NAME}/config:/etc/pdmii
      - /opt/telos/pdmx-${INSTANCE_NAME}/data:/var/opt/audio
    tmpfs:
      - /run/pdmx

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true
  ext1macvlan:
    name: ext1macvlan
    external: true

volumes:
  data:
  config:
