services:
  vxs:
    image: ${REPOSITORY:-quay.io/telosalliance/vxs}:${TAG:-latest}
    container_name: vxs-${INSTANCE_NAME}
    hostname: vxs-${INSTANCE_NAME}
    restart: unless-stopped
    user: ${TAC_UID:-0}:${TAC_GID:-0}
    sysctls:
      fs.mqueue.msg_max: 1024
    ulimits:
      rtprio: 60
      memlock: -1
    cap_add:
      - net_bind_service
    cap_drop:
      - all
    environment:
      - IFACE_AOIP_SYNC=${IFACE_AOIP_SYNC:-eth1}
      - SYNC_CLOCK=${SYNC_CLOCK:-ptp-snooping}
      - SYNC_PTP_DOMAIN=${SYNC_PTP_DOMAN:-0}
    networks:
      telosmacvlan:
        ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
      ext1macvlan:
        ipv4_address: ${IFACE_EXT_IPV4_ADDRESS}
    volumes:
      - /dev/log:/dev/log
      - /opt/telos/vxs-${INSTANCE_NAME}/config:/etc/telos_vx
      - /opt/telos/vxs-${INSTANCE_NAME}/data:/var/lib/telos_vx
    tmpfs:
      - /run/telos_vx

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true
  ext1macvlan:
    name: ext1macvlan
    external: true

volumes:
  data:
  config:
