version: '3.3'
services:
  fm-transport:
    image: ${REPOSITORY:-quay.io/telosalliance/fm-transport}:${TAG:-latest}
    container_name: fm-transport-${INSTANCE_NAME}
    hostname: fm-transport-${INSTANCE_NAME}
    restart: unless-stopped
    cap_add:
      - SYS_NICE
      - IPC_LOCK
      - NET_BROADCAST
      - SYS_RAWIO
      - NET_BIND_SERVICE
      - NET_RAW
    user: ${TAC_UID:-0}:${TAC_GID:-0}
    networks:
      telosmacvlan:
        ipv4_address: ${AOIP_IPV4_ADDRESS}
      ext1macvlan:
        ipv4_address: ${EXT_IPV4_ADDRESS}
    environment:
      - IFACE_AOIP=${IFACE_AOIP:-eth0}
      - EX_CLOCK_SOURCE=${EX_CLOCK_SOURCE:-ptp-snooping}
      - EX_AOIP_CLOCK=${EX_AOIP_CLOCK:-0}
      - EX_PTP_DOMAIN=${EX_PTP_DOMAIN:-0}
      - EX_AOIP_TASK_RATE=${EX_AOIP_TASK_RATE:-200}
      - EX_RT_CPU
      - HTTP_PORT=${HTTP_PORT:-80}
    volumes:
      - /opt/telos/fm-transport-${INSTANCE_NAME}/mpx-data:/data
     
networks:
  telosmacvlan:
    external: true
  ext1macvlan:
    external: true