services:
  coturn:
    image: ${REPOSITORY:-quay.io/telosalliance/coturn}:${TAG:-latest}
    container_name: coturn-${INSTANCE_NAME}
    hostname: coturn-${INSTANCE_NAME}
    restart: unless-stopped
    command: --log-file=stdout --realm=$$DomainName --server-name=$$DomainName --fingerprint --external-ip=$${ExternalIP:-$$(detect-external-ip)}/$$InternalIP --relay-ip=$${ExternalIP:-$$(detect-external-ip)}/$$InternalIP --min-port=$$MinimumPort --max-port=$$MaximumPort --user=$$TurnUsername:$$TurnPassword --lt-cred-mech --stale-nonce=0 --channel-lifetime=0
    environment:
      - DomainName=${DOMAINNAME}
      - InternalIP=${IFACE_AOIP_IPV4_ADDRESS}
      - ExternalIP=${PUBLICIP}
      - TurnUsername=${TURNUSERNAME}
      - TurnPassword=${TURNPASSWORD}
      - MinimumPort=${MINIMUMPORT:-49152} 
      - MaximumPort=${MAXIMUMPORT:-65535}
    networks:
      telosmacvlan:
        ipv4_address: ${COTURN_TELOSMACVLAN}
    volumes:
      - /opt/telos/coturn-${INSTANCE_NAME}/coturn_data:/var/lib/coturn:z
      - /opt/telos/nginx-${INSTANCE_NAME}/ssl:/certs:ro

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true

volumes:
  coturn_data:
