services:
  iqs:
    image: ${REPOSITORY:-quay.io/telosalliance/iqs}:${TAG:-latest}
    container_name: iqs-${INSTANCE_NAME}
    hostname: iQs-${INSTANCE_NAME}
    restart: unless-stopped
    sysctls:
      - net.ipv4.igmp_max_memberships=256
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    networks:
      telosmacvlan:
        ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
    volumes:
      - /opt/telos/iqs-{INSTANCE_NAME}/config:/config

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true

volumes:
  config:
