services:
  zephyr_connect:
    image: ${REPOSITORY:-quay.io/telosalliance/zephyr-connect}:${TAG:-latest}
    container_name: zephyr-connect-${INSTANCE_NAME}
    hostname: zephyr-connect-${INSTANCE_NAME}
    restart: unless-stopped
    command: "/bin/ips-start"
    sysctls:
      net.ipv4.igmp_max_memberships: 256
    cap_add:
      - SYS_NICE
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
    environment:
     - IFACE_AOIP=${IFACE_AOIP:-eth0}
     - IFACE_EXT=${IFACE_AOIP:-eth0}
    networks:
      telosmacvlan:
          ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
    volumes:
     - /opt/telos/zephyr-connect-${INSTANCE_NAME}/ZephConnConfig:/etc/Axia/EngConf
     - /opt/telos/zephyr-connect-${INSTANCE_NAME}/ZephConnData:/var/lib/ZephConn
    tmpfs:
     - /tmp

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true

volumes:
    ZephConnConfig:
    ZephConnData:
