services:
  zephyr_connect:
    image: ${REPOSITORY:-quay.io/telosalliance/zephyr-connect}:${TAG:-latest}
    container_name: zephyr-connect-${INSTANCE_NAME}
    hostname: zephyr-connect-${INSTANCE_NAME}
    restart: unless-stopped
    command: "/bin/ips-start"
    cap_add:
      - SYS_NICE
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
    environment:
     - IFACE_AOIP=${IFACE_AOIP}
     - IFACE_EXT=${IFACE_EXT}
    network_mode: "host"
    volumes:
     - /opt/telos/zephyr-connect-${INSTANCE_NAME}/ZephConnConfig:/etc/Axia/EngConf
     - /opt/telos/zephyr-connect-${INSTANCE_NAME}/ZephConnData:/var/lib/ZephConn
    tmpfs:
     - /tmp

volumes:
    ZephConnConfig:
    ZephConnData:
