services:
  vip:
    image: ${REPOSITORY:-quay.io/telosalliance/intercom}:${TAG:-latest}
    restart: unless-stopped
    privileged: true
    cap_add:
      - SYS_NICE
    environment:
      - DEVTYPE=vip16
    networks:
      telosmacvlan:
        ipv4_address: ${IPV4_ADDRESS}
    volumes:
      - config:/config

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true

volumes:
  config:
