services:
  ptp4l:
    image: ${REPOSITORY:-telosalliance/ptp4l}:${TAG:-latest}
    container_name: ptp4l-${INSTANCE_NAME}
    hostname: ptp4l-${INSTANCE_NAME}
    restart: unless-stopped
    command: ${PTP4L_ARGS}
    privileged: true
    networks:
      telosmacvlan:
        ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
    volumes:
      - /opt/telos/ptp-${INSTANCE_NAME}/dev/log:/dev/log

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true
