version: "3.4"

networks:
  grafana:
    driver: bridge

volumes:
  loki-config:
  loki-data:
  prometheus-config:
  prometheus-data:
  promtail-config:
  promtail-data:
  grafana:

services:
  prometheus:
    image: prom/prometheus:v2.16.0
    user: 1000:1000
    volumes:
      - prometheus-config:/etc/prometheus/
      - prometheus-data:/prometheus/
    command:
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - grafana

  loki:
    image: grafana/loki:1.4.1
    user: 1000:1000
    ports:
      - 3100:3100
    volumes:
      - loki-config:/etc/loki/
      - loki-data:/tmp/loki/
    networks:
      - grafana

  promtail:
    image: grafana/promtail:v1.3.0
    user: 1000:1000
    volumes:
      - promtail-data:/var/log/
      - promtail-config/:/etc/promtail/
    networks:
      - grafana

  grafana:
    image: grafana/grafana:7.1.5
    user: 1000:1000
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - grafana
