services:
  pdmx:
    image: ${REPOSITORY:-quay.io/telosalliance/pdmx}:${TAG:-latest}
    container_name: pdmx-${INSTANCE_NAME}
    hostname: pdmx-${INSTANCE_NAME}
    restart: unless-stopped
    cap_add:
      - SYS_NICE
      - net_bind_service
    environment:
      - STUDIO=${INSTANCE_NAME}
      - IFACE_AOIP=${IFACE_AOIP}
    network_mode: host
    volumes:
      - /dev/log:/dev/log
      - /opt/telos/pdmx-${INSTANCE_NAME}/config:/etc/pdmii
      - /opt/telos/pdmx-${INSTANCE_NAME}/data:/var/opt/audio
    tmpfs:
      - /run/pdmx

volumes:
  data:
  config:
