services:
  forza:
    image: ${REPOSITORY:-quay.io/telosalliance/forza-fm}:${FORZA_TAG:-latest}
    container_name: forza-fm-${STACK_NAME}
    hostname: forza-fm-${STACK_NAME}
    restart: unless-stopped
    user: ${TAC_UID:-0}:${TAC_GID:-0}
    cap_add:
      - SYS_NICE
      - IPC_LOCK
      - SYS_RAWIO
      - NET_BROADCAST
      - NET_BIND_SERVICE
      - NET_RAW
    environment:
      - HTTP_PORT=${FORZA_HTTP_PORT:-80}
      - IFACE_AOIP=${IFACE_AOIP:-eth0}
      - EX_CLOCK_SOURCE=${EX_CLOCK_SOURCE:-ptp-snooping}
      - EX_AOIP_CLOCK=${EX_AOIP_CLOCK:-0}
      - EX_PTP_DOMAIN=${EX_PTP_DOMAIN:-0}
      - EX_AOIP_TASK_RATE=${FORZA_AOIP_TASK_RATE:-200}
      - EX_RT_CPU=${FORZA_EX_RT_CPU}
    networks:
      telosmacvlan:
        ipv4_address: ${FORZA_IFACE_AOIP_IPV4_ADDRESS}
    volumes:
      - /opt/telos/forza-fm-${INSTANCE_NAME}/forza_data:/data

  fm-transport:
    image: ${REPOSITORY:-quay.io/telosalliance/fm-transport}:${FM_TRANSPORT_TAG:-latest}
    container_name: fm-transport-${STACK_NAME}
    hostname: fm-transport-${STACK_NAME}
    restart: unless-stopped
    user: ${TAC_UID:-0}:${TAC_GID:-0}
    environment:
      - HTTP_PORT=${FM_TRANSPORT_HTTP_PORT:-80}
      - IFACE_AOIP=${IFACE_AOIP:-eth0}
    networks:
      telosmacvlan:
        ipv4_address: ${FM_TRANSPORT_IFACE_AOIP_IPV4_ADDRESS}
    volumes:
      - /opt/telos/fm-transport-${STACK_NAME}/data:/data

  omnia-rds:
    image: ${REPOSITORY:-quay.io/telosalliance/omnia-rds-generator}:${OMNIA_RDS_TAG:-latest}
    container_name: omnia-rds-${STACK_NAME}
    hostname: omnia-rds-${STACK_NAME}
    restart: unless-stopped
    user: ${TAC_UID:-0}:${TAC_GID:-0}
    environment:
      - HTTP_PORT=${OMNIA_RDS_HTTP_PORT:-80}
    networks:
      telosmacvlan:
        ipv4_address: ${OMNIA_RDS_IFACE_AOIP_IPV4_ADDRESS}
    volumes:
      - /opt/telos/omnia-rds-${STACK_NAME}/data:/data

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true

volumes:
  forza_data:
