version: '3'
services:
  forza:
    image: ${REPOSITORY:-quay.io/telosalliance/forza}:${TAG:-latest}
    container_name: forza-${INSTANCE_NAME}
    hostname: forza-${INSTANCE_NAME}
    restart: unless-stopped
    cap_add:
      - SYS_NICE
      - IPC_LOCK
      - SYS_RAWIO
      - NET_BROADCAST
      - NET_BIND_SERVICE
      - NET_RAW
    user: ${TAC_UID:-0}:${TAC_GID:-0}
    networks:
      telosmacvlan:
        ipv4_address: ${IPV4_ADDRESS}
    environment:
      - IFACE_AOIP=${IFACE_AOIP:-eth0}
      - EX_CLOCK_SOURCE=${EX_CLOCK_SOURCE:-ptp-snooping}
      - EX_AOIP_CLOCK=${EX_AOIP_CLOCK:-0}
      - EX_PTP_DOMAIN=${EX_PTP_DOMAIN:-0}
      - EX_AOIP_TASK_RATE=${EX_AOIP_TASK_RATE:-1000}
      - EX_RT_CPU
      - HTTP_PORT=${HTTP_PORT:-80}
    volumes:
      - /opt/telos/forza-${INSTANCE_NAME}/forza_data:/forza_data

volumes:
  forza_data:

networks:
  telosmacvlan:
    external:
      name: telosmacvlan
