services:
  nginx:
    image: ${REPOSITORY:-quay.io/telosalliance/nginx}:${NGINX_TAG:-latest}
    container_name: nginx-${STACK_NAME}
    hostname: nginx-${STACK_NAME}
    restart: unless-stopped
    networks:
      telosmacvlan:
        ipv4_address: ${NGINX_IFACE_AOIP_IPV4_ADDRESS}
      ext1macvlan:
        ipv4_address: ${NGINX_IFACE_EXT_IPV4_ADDRESS}
    volumes:
      - /opt/telos/nginx-${STACK_NAME}/conf.d:/etc/nginx/conf.d 
      - /opt/telos/nginx-${STACK_NAME}/ssl:/etc/nginx/ssl 
      - /opt/telos/nginx-${STACK_NAME}/www:/var/www

  ta_auto_proxy:
    image: ${REPOSITORY:-quay.io/telosalliance/ta-auto-proxy}:${TAP_TAG:-latest}
    container_name: ta-auto-proxy-${STACK_NAME}
    hostname: ta-auto-proxy-${STACK_NAME}
    restart: unless-stopped
    stop_grace_period: 4s
    environment:
      - NGINX_CONTAINER_NAME=nginx-${STACK_NAME}
    volumes:
      - /opt/telos/nginx-${STACK_NAME}:/etc/nginx
      - /var/run/docker.sock:/var/run/docker.sock

  acme:
    image:  ${REPOSITORY:-quay.io/telosalliance/acme}:${ACME_TAG:-latest}
    container_name: acme-${STACK_NAME}
    hostname: acme-${STACK_NAME}
    environment:
      - CERT_DOMAIN=${CERT_DOMAIN}
      - CERT_EMAIL=${CERT_EMAIL}
      - CERT_MODE=${CERT_MODE:-production}
      - NGINX_CONTAINER_NAME=nginx-${STACK_NAME}
    networks:
      ext1macvlan:
        ipv4_address: ${ACME_IFACE_EXT_IPV4_ADDRESS}
    volumes:
      - /opt/telos/acme-${STACK_NAME}:/acme.sh
      - /opt/telos/nginx-${STACK_NAME}/www:/var/www
      - /opt/telos/nginx-${STACK_NAME}/ssl:/etc/nginx/ssl
      - /opt/telos/nginx-${STACK_NAME}/conf.d/option.d:/etc/nginx/conf.d/option.d
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true
  ext1macvlan:
    name: ext1macvlan
    external: true
