version: '2.4'
services:
  beacon:
    restart: unless-stopped
    image: ${REPOSITORY:-quay.io/telosalliance/beacon}:${TAG:-latest}
    container_name: beacon-${INSTANCE_NAME}
    hostname: beacon-${INSTANCE_NAME}
    networks:
      telosmacvlan:
           ipv4_address: ${IPV4_ADDRESS}
    volumes:
      - /opt/telos/beacon-${INSTANCE_NAME}:/config:z
      - /etc/telos:/etc/telos:ro
networks:
  telosmacvlan:
    external:
      name: telosmacvlan
