services:
  beacon:
    image: ${REPOSITORY:-quay.io/telosalliance/beacon}:${TAG:-latest}
    container_name: beacon-${INSTANCE_NAME}
    hostname: beacon-${INSTANCE_NAME}
    restart: unless-stopped
    networks:
      telosmacvlan:
           ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
    volumes:
      - /opt/telos/beacon-${INSTANCE_NAME}:/config:z
      - /etc/telos:/etc/telos:ro

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true
