version: '3.3'
services:
  zephyr_connect:
    restart: unless-stopped
    image: ${REPOSITORY:-quay.io/telosalliance/zephyr-connect}:${TAG:-latest}
    container_name: zephyr_connect
    command: "/bin/ips-start"
    cap_add:
      - SYS_NICE
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
    networks:
      telosmacvlan:
          ipv4_address: ${AOIP_IPV4_ADDRESS}
      ext1macvlan:
          ipv4_address: ${EXT_IPV4_ADDRESS}
    environment:
     - IFACE_AOIP=${IFACE_AOIP}
     - IFACE_EXT=${IFACE_EXT}
    volumes:
     - /opt/telos/zephyr_connect-${INSTANCE_NAME}/ZephConnConfig:/etc/Axia/EngConf
     - /opt/telos/zephyr_connect-${INSTANCE_NAME}/ZephConnData:/var/lib/ZephConn
    tmpfs:
     - /tmp
    sysctls:
      net.ipv4.igmp_max_memberships: 256


networks:
  telosmacvlan:
    external:
      name: telosmacvlan
  ext1macvlan:
    external:
      name: ext1macvlan
volumes:
    ZephConnConfig:
    ZephConnData:
