version: '2.4'
services:
  pdmx:
    restart: unless-stopped
    image: ${REPOSITORY:-quay.io/telosalliance/pdmx}:${TAG:-latest}
    container_name: pdmx-${INSTANCE_NAME}
    hostname: pdmx:${INSTANCE_NAME}
    environment:
      STUDIO: ${INSTANCE_NAME}
    networks:
      telosmacvlan:
        ipv4_address: ${IPV4_ADDRESS}
    sysctls:
      #### Make sure tcp sockets fail quickly if network dies ####
      # Idle time until first keepalive packet sent
      - net.ipv4.tcp_keepalive_time=3
      # Time between subsequent keepalive packets
      - net.ipv4.tcp_keepalive_intvl=3
      # How many keepalive packets before declare connection dead
      - net.ipv4.tcp_keepalive_probes=3
      # Number of retries of unacknowledged packets (exponential backoff; about 12 seconds)
      - net.ipv4.tcp_retries2=5
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - /dev/log:/dev/log
      - /opt/telos/pdmx-${INSTANCE_NAME}/config:/etc/pdmii
      - /opt/telos/pdmx-${INSTANCE_NAME}/data:/var/opt/audio
    tmpfs:
      - /run/pdmx

volumes:
  data:
  config:

networks:
  telosmacvlan:
    external:
      name: telosmacvlan
