services:
  forza:
    image: ${REPOSITORY:-quay.io/telosalliance/forza}:${TAG:-latest}
    container_name: forza-hds-${INSTANCE_NAME}
    hostname: forza-hds-${INSTANCE_NAME}
    restart: unless-stopped
    user: ${TAC_UID:-0}:${TAC_GID:-0}
    cap_add:
      - SYS_NICE
      - IPC_LOCK
      - SYS_RAWIO
      - NET_BROADCAST
      - NET_BIND_SERVICE
      - NET_RAW
    environment:
      - HTTP_PORT=${HTTP_PORT:-80}
      - IFACE_AOIP=${IFACE_AOIP:-eth1}
      - EX_CLOCK_SOURCE=${EX_CLOCK_SOURCE:-ptp-snooping}
      - EX_AOIP_CLOCK=${EX_AOIP_CLOCK:-0}
      - EX_PTP_DOMAIN=${EX_PTP_DOMAIN:-0}
      - EX_AOIP_TASK_RATE=${EX_AOIP_TASK_RATE:-1000}
      - EX_RT_CPU=${EX_RT_CPU}
    networks:
      telosmacvlan:
        ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
      ext1macvlan:
        ipv4_address: ${IFACE_EXT_IPV4_ADDRESS}
    volumes:
      - /opt/telos/forza-hds-${INSTANCE_NAME}/forza_data:/data

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true
  ext1macvlan:
    name: ext1macvlan
    external: true

volumes:
  forza_data:
