services:
  altus:
    image: ${REPOSITORY:-quay.io/telosalliance/altus}:${TAG:-latest}
    container_name: altus-${INSTANCE_NAME}
    hostname: altus-${INSTANCE_NAME}
    restart: unless-stopped
    sysctls:
      - net.ipv4.igmp_max_memberships=256
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    environment:
      - NDI_CONFIG_DIR=/root/.newtek
      - TA_AUTO_PROXY=true
    networks:
      telosmacvlan:
        ipv4_address: ${IFACE_AOIP_IPV4_ADDRESS}
      ext1macvlan:
        ipv4_address: ${IFACE_EXT_IPV4_ADDRESS}
    volumes:
      - /opt/telos/altus-${INSTANCE_NAME}/config:/config
      - /opt/telos/altus-${INSTANCE_NAME}/logs:/var/logs

networks:
  telosmacvlan:
    name: telosmacvlan
    external: true
  ext1macvlan:
    name: ext1macvlan
    external: true

volumes:
  config:
