services:
  altus:
    image: ${REPOSITORY:-quay.io/telosalliance/altus}:${TAG:-latest}
    container_name: altus-${INSTANCE_NAME}
    hostname: altus-${INSTANCE_NAME}
    restart: unless-stopped
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    environment:
      - NDI_CONFIG_DIR=/root/.newtek
      - TA_AUTO_PROXY=true
    network_mode: host
    volumes:
      - /opt/telos/altus-${INSTANCE_NAME}/config:/config
      - /opt/telos/altus-${INSTANCE_NAME}/logs:/var/logs

volumes:
  config:
