services:
  mp500:
    image: ${REPOSITORY:-quay.io/telosalliance/vero}:${TAG:-latest}
    container_name: vero-${INSTANCE_NAME}
    hostname: vero-${INSTANCE_NAME}
    restart: unless-stopped
    user: ${FORZA_UID:-0}:${FORZA_GID:-0}
    command: "exsvcmgr -c /model/mp500.json EngineCore"
    cap_add:
      - SYS_NICE
      - IPC_LOCK
      - SYS_RAWIO
      - NET_BROADCAST
      - NET_BIND_SERVICE
      - NET_RAW
      # Note that NET_BIND_SERVICE and NET_RAW are available by default
      # in a Docker container.  I list them as needed for documentation
      # or for those that may want to drop other capabilities
    environment:
      - HTTP_PORT
      - EX_AOIP_INTERFACE
      - EX_CLOCK_SOURCE
      - EX_AOIP_CLOCK
      - EX_PTP_DOMAIN
      - EX_RT_CPU
    network_mode: "host"
    volumes:
      - /opt/telos/vero-${INSTANCE_NAME}/mp500_data:/data

volumes:
  mp500_data:

# Note that docker compose will automatically prepend this volume
# name with the name of the directory containing the docker-compose.yml
# file.  That way, different containers will have different volumes and
# not end up trying to share the same database file.
